paths:
  frames_root_base: "./data/final/cameras/breathing/sync_fps"
  cosmed:
    sofia: "./data/final/cosmed/sofia_cosmed.xlsx"
    mallory: "./data/final/cosmed/mallory_cosmed.xlsx"
  results_dir: "VT_Results_SyncFPS_2"

experiment:
  cameras: ["gray", "phone", "olympus", "flir"]
  participants: ["mallory", "sofia"]
  takes_order: [0, 1, 2, 3]     
  rois_to_test: ["chest", "abdomen", "segmented"]
  pca_settings: [false, true]
  fps:
    sofia: 9.7
    mallory: 9.0

signal:
  lo_hz: 0.07
  hi_hz: 1.0
  burn_s: 2.0

cotracker:
  max_inference_dim: 480
  grid_size: 30
